include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: false
    strict-inference: false

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
